repositories:
  remote:
   - http://repo1.maven.org/maven2

artifacts:
  javax_javaee: javax:javaee-api:jar:7.0
  javax_annotation: com.google.code.findbugs:jsr305:jar:2.0.1

  # GWT Dependencies
  gwt_user: com.google.gwt:gwt-user:jar:2.6.0-rc4
  gwt_dev: com.google.gwt:gwt-dev:jar:2.6.0-rc4
  javax_validation: javax.validation:validation-api:jar:1.0.0.GA
  javax_validation_sources: javax.validation:validation-api:jar:sources:1.0.0.GA

  #
  # GIN and associated dependencies
  gwt_gin: com.google.gwt.inject:gin:jar:2.1.2
  google_guice: com.google.inject:guice:jar:3.0
  google_guice_assistedinject: com.google.inject.extensions:guice-assistedinject:jar:3.0
  aopalliance: aopalliance:aopalliance:jar:1.0 # Required for guice

  # Library under demonstration
  replicant: org.realityforge.replicant:replicant:jar:0.5.1-11-ga2a6da6

  # Dependency used for session management
  simple_session_filter: org.realityforge.ssf:simple-session-filter:jar:0.1

  #
  # Used in mapping entities to json
  # TODO: This hard dependency exists in the generated servlet code for gwt-rpc. It should be removed!
  jackson_core: org.codehaus.jackson:jackson-core-asl:jar:1.9.4
  jackson_mapper: org.codehaus.jackson:jackson-mapper-asl:jar:1.9.4

  # Supporting GWT libraries
  gwt_datatypes: org.realityforge.gwt.datatypes:gwt-datatypes:jar:0.1
  gwt_websockets: org.realityforge.gwt.websockets:gwt-websockets:jar:0.1
  gwt_cache_filter: org.realityforge.gwt.cache-filter:gwt-cache-filter:jar:0.3

  mockito: org.mockito:mockito-all:jar:1.9.5

  # Jersey MVC implementation. Used as part of the login process..
  jersey_mvc: org.glassfish.jersey.ext:jersey-mvc:jar:2.5
  jersey_mvc_jsp: org.glassfish.jersey.ext:jersey-mvc-jsp:jar:2.5
