repositories:
  remote:
   - http://repo1.maven.org/maven2

artifacts:
  javax_javaee: javax:javaee-api:jar:7.0
  javax_jsr305: com.google.code.findbugs:jsr305:jar:3.0.0
  findbugs_annotations: com.google.code.findbugs:annotations:jar:3.0.0

  # GWT Dependencies
  gwt_user: com.google.gwt:gwt-user:jar:2.7.0
  gwt_dev: com.google.gwt:gwt-dev:jar:2.7.0
  gwt_servlet: com.google.gwt:gwt-servlet:jar:2.7.0

  #
  # GIN and associated dependencies
  gwt_gin: com.google.gwt.inject:gin:jar:2.1.2
  google_guice: com.google.inject:guice:jar:3.0
  google_guice_assistedinject: com.google.inject.extensions:guice-assistedinject:jar:3.0
  aopalliance: aopalliance:aopalliance:jar:1.0 # Required for guice

  # Library under demonstration
  replicant: org.realityforge.replicant:replicant:jar:0.5.50

  # Dependency used for session management
  simple_session_filter: org.realityforge.ssf:simple-session-filter:jar:0.5
  field_filter: org.realityforge.rest.field_filter:rest-field-filter:jar:0.4

  #
  # Used in mapping entities to json
  # TODO: This hard dependency exists in the generated servlet code for gwt-rpc. It should be removed!
  jackson_core: org.codehaus.jackson:jackson-core-asl:jar:1.9.13
  jackson_mapper: org.codehaus.jackson:jackson-mapper-asl:jar:1.9.13

  # Supporting GWT libraries
  gwt_datatypes: org.realityforge.gwt.datatypes:gwt-datatypes:jar:0.8
  gwt_cache_filter: org.realityforge.gwt.cache-filter:gwt-cache-filter:jar:0.6

  gwt_webpoller: org.realityforge.gwt.webpoller:gwt-webpoller:jar:0.8

  gwt_lognice: org.realityforge.gwt.lognice:gwt-lognice:jar:0.2

  mockito: org.mockito:mockito-all:jar:1.9.5

  gwt_property_source: org.realityforge.gwt.property-source:gwt-property-source:jar:0.2
