# DO NOT EDIT: File is auto-generated
source 'https://rubygems.org'
gem 'braid', '= 1.0.21'
gem 'buildr', '= 1.5.4'
gem 'buildr_plus', '= 1.0.0', :path => 'vendor/tools/buildr_plus'
gem 'dbt', '= 0.10.0.dev', :path => 'vendor/tools/dbt'
gem 'domgen', '= 0.19.0.dev', :path => 'vendor/tools/domgen'
gem 'maruku'
gem 'redfish', '= 0.2.2.dev', :path => 'vendor/tools/redfish'
gem 'tiny_tds', '= 1.0.5'
